package foro.modelo;
// Generated 12-jun-2012 13:39:35 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int id;
     private String nick;
     private String password;
     private Set topics = new HashSet(0);
     private Set mensajeses = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int id, String nick, String password) {
        this.id = id;
        this.nick = nick;
        this.password = password;
    }
    public Usuario(int id, String nick, String password, Set topics, Set mensajeses) {
       this.id = id;
       this.nick = nick;
       this.password = password;
       this.topics = topics;
       this.mensajeses = mensajeses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNick() {
        return this.nick;
    }
    
    public void setNick(String nick) {
        this.nick = nick;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getTopics() {
        return this.topics;
    }
    
    public void setTopics(Set topics) {
        this.topics = topics;
    }
    public Set getMensajeses() {
        return this.mensajeses;
    }
    
    public void setMensajeses(Set mensajeses) {
        this.mensajeses = mensajeses;
    }




}


