package foro.modelo;
// Generated 12-jun-2012 13:39:35 by Hibernate Tools 3.4.0.CR1


import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Topic generated by hbm2java
 */
public class Topic  implements java.io.Serializable {


     private int id;
     private Categoria categoria;
     private Usuario usuario;
     private String titulo;
     private Date fecha;
     private List<Mensajes> mensajeses = new ArrayList<Mensajes>();

    public Topic() {
    }

	
    public Topic(int id, Categoria categoria, Usuario usuario, String titulo, Date fecha) {
        this.id = id;
        this.categoria = categoria;
        this.usuario = usuario;
        this.titulo = titulo;
        this.fecha = fecha;
    }
    public Topic(int id, Categoria categoria, Usuario usuario, String titulo, Date fecha, List<Mensajes> mensajeses) {
       this.id = id;
       this.categoria = categoria;
       this.usuario = usuario;
       this.titulo = titulo;
       this.fecha = fecha;
       this.mensajeses = mensajeses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public List<Mensajes> getMensajeses() {
        return this.mensajeses;
    }
    
    public void setMensajeses(List<Mensajes> mensajeses) {
        this.mensajeses = mensajeses;
    }




}


